import { stagingBudget } from '../js/staging.js';
const presets=[{wetKg:420000,dryKg:28000,ispS:310},{wetKg:110000,dryKg:9000,ispS:350},{wetKg:30000,dryKg:3200,ispS:455},{wetKg:9000,dryKg:1100,ispS:455}];
const mission=document.querySelector('#mission'),editor=document.querySelector('#stageEditor'),rocket=document.querySelector('#rocket'),budgetEl=document.querySelector('#budget');
function formatMission(){mission.querySelector('[data-output="stageCount"]').textContent=document.querySelector('#stageCount').value;mission.querySelector('[data-output="payload"]').textContent=`${Number(document.querySelector('#payload').value).toLocaleString()} kg`;mission.querySelector('[data-output="target"]').textContent=`${Number(document.querySelector('#target').value).toLocaleString()} m/s`}
function buildEditors(){const count=Number(document.querySelector('#stageCount').value);editor.innerHTML='';for(let i=0;i<count;i++){const p=presets[i];editor.insertAdjacentHTML('beforeend',`<article class="stage-card"><h3>Stage ${i+1}${i===count-1?' · final':''}</h3><div class="stage-fields"><label>Wet kg<input data-stage="${i}" data-key="wetKg" type="number" min="1" value="${p.wetKg}"></label><label>Dry kg<input data-stage="${i}" data-key="dryKg" type="number" min="1" value="${p.dryKg}"></label><label>Isp s<input data-stage="${i}" data-key="ispS" type="number" min="1" value="${p.ispS}"></label></div></article>`)}editor.querySelectorAll('input').forEach(x=>x.addEventListener('input',update));update()}
function getStages(){return [...editor.querySelectorAll('.stage-card')].map(card=>Object.fromEntries([...card.querySelectorAll('input')].map(x=>[x.dataset.key,Number(x.value)])))}
function update(){formatMission();const stages=getStages();if(!stages.length)return;const target=Number(document.querySelector('#target').value),result=stagingBudget(stages,Number(document.querySelector('#payload').value),target),margin=result.finalAvailable-result.finalRequired;
 document.querySelector('#required').textContent=`${result.finalRequired.toFixed(0)} m/s`;document.querySelector('#available').textContent=`${result.finalAvailable.toFixed(0)} m/s`;document.querySelector('#total').textContent=`${result.total.toFixed(0)} m/s`;document.querySelector('#margin').textContent=`${margin>=0?'+':''}${margin.toFixed(0)} m/s`;document.querySelector('#margin').className=margin>=0?'status-good':'status-bad';document.querySelector('#warning').textContent=stages.some(s=>s.dryKg>=s.wetKg)?'Each wet mass must exceed its dry mass.':margin<0?'The final stage cannot close the requested Δv budget.':'The ideal Δv budget closes.';
 rocket.querySelectorAll('.rocket-stage').forEach(x=>x.remove());const max=Math.max(...stages.map(s=>s.wetKg));[...stages].reverse().forEach((s,ri)=>{const i=stages.length-1-ri,el=document.createElement('div');el.className='rocket-stage';el.style.width=`${28+68*Math.sqrt(s.wetKg/max)}%`;el.style.height=`${50+55*Math.sqrt(s.wetKg/max)}px`;el.textContent=`S${i+1} · ${(s.wetKg/1000).toFixed(1)} t`;rocket.insertBefore(el,rocket.querySelector('.rocket-plume'))});
 budgetEl.innerHTML='<strong>Stage Δv</strong>'+result.deltas.map((dv,i)=>`<div class="budget-row"><span>Stage ${i+1}</span><div class="budget-bar"><i style="width:${Math.min(100,dv/Math.max(target,...result.deltas)*250)}%"></i></div><b>${(dv/1000).toFixed(2)} km/s</b></div>`).join('');
}
document.querySelector('#stageCount').addEventListener('input',()=>{formatMission();buildEditors()});document.querySelector('#payload').addEventListener('input',update);document.querySelector('#target').addEventListener('input',update);buildEditors();

