import {ALPHA_CENTAURI_DISTANCE_LY,AU_KM,LIGHT_YEAR_KM,SUN_MU_KM3_S2,SUN_RADIUS_KM,solarOberthScenario,stateOnConic,stateOnEllipse} from '../js/oberth.js?v=20260902-3';

const $=selector=>document.querySelector(selector);
const parkingAltitude=$('#parkingAltitude'),perihelion=$('#perihelion'),targetSpeed=$('#targetSpeed'),progress=$('#progress'),orbitCanvas=$('#orbitCanvas'),ctx=orbitCanvas.getContext('2d');
const colors={earth:'#54d6dd',target:'#ffb14e',dive:'#90a1a8'};
let model,route='oberth',playing=false,lastFrame=0;

function canvasSize(){const rect=orbitCanvas.getBoundingClientRect(),ratio=Math.min(2,devicePixelRatio||1),width=Math.max(1,Math.round(rect.width*ratio)),height=Math.max(1,Math.round(rect.height*ratio));if(orbitCanvas.width!==width||orbitCanvas.height!==height){orbitCanvas.width=width;orbitCanvas.height=height}return{width,height,ratio}}
const fmt=value=>`${value.toFixed(value>=100?1:2)} km/s`;
const circlePoints=(radius,count=360)=>{const points=[];for(let i=0;i<=count;i++){const a=2*Math.PI*i/count;points.push([radius*Math.cos(a),radius*Math.sin(a)])}return points};
const divePoints=(count=360)=>{const points=[];for(let i=0;i<=count;i++)points.push(stateOnEllipse(SUN_MU_KM3_S2,model.periapsis,model.apoapsis,-Math.PI+2*Math.PI*i/count).position);return points};
const alphaDistance=ALPHA_CENTAURI_DISTANCE_LY*LIGHT_YEAR_KM;
const conicPositionAtRadius=radius=>{const anomaly=Math.acos(Math.max(-1,Math.min(1,(model.targetConic.p/radius-1)/model.targetConic.e)));return stateOnConic(SUN_MU_KM3_S2,model.targetConic.p,model.targetConic.e,anomaly).position};
const targetPosition=fraction=>{const start=route==='direct'?AU_KM:model.periapsis,radius=Math.exp(Math.log(start)+(Math.log(alphaDistance)-Math.log(start))*fraction);return conicPositionAtRadius(radius)};
const targetPoints=maximumRadius=>{const points=[];for(let i=0;i<=420;i++){const radius=Math.exp(Math.log(model.periapsis)+(Math.log(maximumRadius)-Math.log(model.periapsis))*i/420);points.push(conicPositionAtRadius(radius))}return points};

function phaseAt(value){
  if(route==='direct'){
    if(value<.25){const f=value/.25,a=model.directTrueAnomaly-2*Math.PI+2*Math.PI*f;return{step:'one',stage:'earth',label:'Circular Earth orbit',position:[AU_KM*Math.cos(a),AU_KM*Math.sin(a)]}}
    if(value<.31)return{step:'two',stage:'direct-burn',label:'Direct injection at 1 AU',position:model.directState.position,pulse:(value-.25)/.06};
    const f=(value-.31)/.69,step=f<.42?'three':f<.76?'four':'five',zoom=Math.max(0,(f-.42)/.58);return{step,stage:'escape',label:step==='five'?'Cruise toward Alpha Centauri':'Coast on common target hyperbola',position:targetPosition(f),zoom};
  }
  if(value<.18){const f=value/.18,a=-Math.PI+2*Math.PI*f;return{step:'one',stage:'earth',label:'Circular Earth orbit',position:[AU_KM*Math.cos(a),AU_KM*Math.sin(a)]}}
  if(value<.24)return{step:'two',stage:'dive-burn',label:'Retrograde burn at 1 AU',position:model.oberthDeparturePosition,pulse:(value-.18)/.06};
  if(value<.58){const f=(value-.24)/.34;return{step:'three',stage:'dive',label:'Coast down the solar dive',position:stateOnEllipse(SUN_MU_KM3_S2,model.periapsis,model.apoapsis,-Math.PI+Math.PI*f).position}}
  if(value<.64)return{step:'four',stage:'oberth-burn',label:'Solar Oberth burn at perihelion',position:[model.periapsis,0],pulse:(value-.58)/.06};
  const f=(value-.64)/.36,step=f<.58?'four':'five';return{step,stage:'escape',label:step==='five'?'Cruise toward Alpha Centauri':'Coast on common target hyperbola',position:targetPosition(f),zoom:f};
}

function drawVectorArrow(point,vector,label,color,project,ratio){const [x,y]=project(point),screen=[vector[0],-vector[1]],norm=Math.hypot(...screen)||1,length=44*ratio,tx=x+screen[0]/norm*length,ty=y+screen[1]/norm*length,angle=Math.atan2(ty-y,tx-x);ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=2*ratio;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(tx,ty);ctx.stroke();ctx.beginPath();ctx.moveTo(tx,ty);ctx.lineTo(tx-9*ratio*Math.cos(angle-.5),ty-9*ratio*Math.sin(angle-.5));ctx.lineTo(tx-9*ratio*Math.cos(angle+.5),ty-9*ratio*Math.sin(angle+.5));ctx.closePath();ctx.fill();ctx.font=`${10*ratio}px ui-monospace,monospace`;ctx.fillText(label,tx+7*ratio,ty)}
function drawOrbit(){
  const {width,height,ratio}=canvasSize(),cx=width/2,cy=height/2,outer=Math.min(width,height)*.43,rMin=SUN_RADIUS_KM,phase=phaseAt(Number(progress.value)/1000),zoom=phase.zoom||0,rMax=Math.exp(Math.log(3*AU_KM)+(Math.log(alphaDistance)-Math.log(3*AU_KM))*zoom);ctx.clearRect(0,0,width,height);
  const project=point=>{const r=Math.hypot(...point),angle=Math.atan2(point[1],point[0]),f=Math.max(0,Math.min(1,Math.log(Math.max(r,rMin)/rMin)/Math.log(rMax/rMin))),rho=18*ratio+(outer-18*ratio)*f;return[cx+rho*Math.cos(angle),cy-rho*Math.sin(angle)]};
  const path=(points,color,widthPx=1,dash=[])=>{ctx.beginPath();points.forEach((point,index)=>{const [x,y]=project(point);index?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle=color;ctx.lineWidth=widthPx*ratio;ctx.setLineDash(dash.map(v=>v*ratio));ctx.stroke();ctx.setLineDash([])};
  path(circlePoints(AU_KM),colors.earth,phase.stage==='earth'?2.6:1,[4,4]);path(divePoints(),colors.dive,phase.stage==='dive'?2.6:1.3);path(targetPoints(rMax),colors.target,phase.stage==='escape'?2.8:1.7);
  ctx.fillStyle='#ffe09a';ctx.shadowColor='#ffe09a';ctx.shadowBlur=16*ratio;ctx.beginPath();ctx.arc(cx,cy,9*ratio,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;
  if(zoom<.16){if(route==='oberth'){drawVectorArrow(model.oberthDeparturePosition,[0,1],'① brake',colors.dive,project,ratio);drawVectorArrow([model.periapsis,0],[0,1],'② Oberth',colors.target,project,ratio)}else{const dv=[model.directState.velocity[0]-model.earthVelocity[0],model.directState.velocity[1]-model.earthVelocity[1]];drawVectorArrow(model.directState.position,dv,'direct burn',colors.target,project,ratio)}}
  if(zoom>.08){const guide=conicPositionAtRadius(rMax*.72),[gx,gy]=project(guide);ctx.fillStyle=colors.target;ctx.font=`${11*ratio}px ui-monospace,monospace`;ctx.fillText(zoom>.82?'Alpha Centauri · 4.25 ly':'toward Alpha Centauri →',gx+7*ratio,gy-7*ratio)}
  const [sx,sy]=project(phase.position);if(phase.pulse!==undefined){const radius=(8+17*Math.sin(Math.PI*phase.pulse))*ratio;ctx.strokeStyle=colors.target;ctx.lineWidth=2*ratio;ctx.globalAlpha=.85;ctx.beginPath();ctx.arc(sx,sy,radius,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}ctx.fillStyle='#fff';ctx.shadowColor='#fff';ctx.shadowBlur=12*ratio;ctx.beginPath();ctx.arc(sx,sy,5*ratio,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;
}

function setSequence(){const content=route==='oberth'?[['1 · Earth orbit','coast to the dive departure phase'],['2 · Brake','enter solar dive'],['3 · Solar dive','coast to perihelion'],['4 · Oberth and escape','join target hyperbola'],['5 · Alpha Centauri','zoom to idealized cruise']]:[['1 · Earth orbit','coast to the direct departure phase'],['2 · Direct burn','join target at 1 AU'],['3 · Escape','common hyperbola'],['4 · Outbound coast','zoom beyond the planets'],['5 · Alpha Centauri','zoom to idealized cruise']];content.forEach(([title,text],index)=>{$(`#step${['One','Two','Three','Four','Five'][index]}Title`).textContent=title;$(`#step${['One','Two','Three','Four','Five'][index]}Text`).textContent=text})}
function updateStage(){const phase=phaseAt(Number(progress.value)/1000),directDegrees=model.directDepartureTrueLongitude*180/Math.PI,oberthDegrees=model.oberthDepartureTrueLongitude*180/Math.PI;$('#progressOutput').textContent=phase.label;$('#phaseNote').textContent=phase.stage==='dive-burn'?`Solar-dive departure is at heliocentric longitude ${oberthDegrees.toFixed(1)}°. The ${fmt(model.oberthEarthExitDeltaV)} parking-orbit burn supplies ${fmt(model.injectionDeltaV)} Earth-relative v∞ retrograde.`:phase.stage==='oberth-burn'?`Add ${fmt(model.burn.deltaV)} at ${model.burn.initialSpeed.toFixed(1)} km/s and enter the target hyperbola.`:phase.stage==='direct-burn'?`Direct departure is at ${directDegrees.toFixed(1)}°, where the target hyperbola crosses 1 AU—not at the ${oberthDegrees.toFixed(1)}° solar-dive departure. The parking-orbit burn is ${fmt(model.directEarthExitDeltaV)}.`:phase.stage==='escape'?`Both choices now follow the same hyperbolic orbit with v∞ = ${targetSpeed.value} km/s; the view expands toward Alpha Centauri.`:route==='direct'?`Earth coasts to the direct departure at ${directDegrees.toFixed(1)}°; the solar-dive route departs separately at ${oberthDegrees.toFixed(1)}°.`:`Earth coasts to the solar-dive departure at ${oberthDegrees.toFixed(1)}°; direct departure is separate at ${directDegrees.toFixed(1)}°.`;document.querySelectorAll('[data-step]').forEach(item=>item.classList.toggle('active',item.dataset.step===phase.step));drawOrbit()}
function updateModel(){model=solarOberthScenario({perihelionSolarRadii:Number(perihelion.value),targetVInfinity:Number(targetSpeed.value),earthParkingAltitudeKm:Number(parkingAltitude.value)});$('#parkingAltitudeOutput').textContent=`${parkingAltitude.value} km`;$('#perihelionOutput').textContent=`${Number(perihelion.value).toFixed(1)} R☉`;$('#targetSpeedOutput').textContent=`${targetSpeed.value} km/s`;$('#injectionDv').textContent=fmt(model.oberthEarthExitDeltaV);$('#oberthDv').textContent=fmt(model.burn.deltaV);$('#totalDv').textContent=fmt(model.totalDeltaV);$('#directDv').textContent=fmt(model.directTotalDeltaV);const saving=model.directTotalDeltaV-model.totalDeltaV;$('#saving').textContent=`${saving>=0?'+':'−'}${Math.abs(saving).toFixed(2)} km/s`;$('#saving').className=saving>=0?'status-good':'status-bad';$('#travelTime').textContent=`${Math.round(model.travelYears).toLocaleString()} yr`;updateStage()}

[parkingAltitude,perihelion,targetSpeed].forEach(input=>input.addEventListener('input',updateModel));progress.addEventListener('input',()=>{playing=false;$('#play').textContent='Play';updateStage()});document.querySelectorAll('[data-route]').forEach(button=>button.addEventListener('click',()=>{route=button.dataset.route;document.querySelectorAll('[data-route]').forEach(item=>item.classList.toggle('accent',item.dataset.route===route));progress.value='0';playing=false;$('#play').textContent='Play';setSequence();updateStage()}));$('#play').addEventListener('click',()=>{if(Number(progress.value)>=1000)progress.value='0';playing=!playing;$('#play').textContent=playing?'Pause':'Play';lastFrame=performance.now()});$('#reset').addEventListener('click',()=>{playing=false;$('#play').textContent='Play';progress.value='0';updateStage()});new ResizeObserver(drawOrbit).observe($('#viewport'));
function animate(time){if(playing){const elapsed=Math.min(50,time-lastFrame);lastFrame=time;let value=Number(progress.value)+elapsed*.075;if(value>=1000){value=1000;playing=false;$('#play').textContent='Replay'}progress.value=String(value);updateStage()}requestAnimationFrame(animate)}
setSequence();updateModel();requestAnimationFrame(animate);
