import {EARTH_MU_KM3_S2,EARTH_RADIUS_KM,GEO_RADIUS_KM,gtoFromEntryScenario,stateOnConic,stateOnEllipse} from '../js/oberth.js?v=20260902-5';

const $=selector=>document.querySelector(selector);
const perigeeAltitude=$('#perigeeAltitude'),apogeeAltitude=$('#apogeeAltitude'),burnAngle=$('#burnAngle'),progress=$('#progress'),orbitCanvas=$('#orbitCanvas'),ctx=orbitCanvas.getContext('2d');
const colors={entry:'#54d6dd',gto:'#ffb14e',geo:'#8bd99d'};
const boundaries={burn1Start:.225,burn1End:.285,burn2Start:.675,burn2End:.735};
let model,playing=false,lastFrame=0;

function canvasSize(){const rect=orbitCanvas.getBoundingClientRect(),ratio=Math.min(2,devicePixelRatio||1),width=Math.max(1,Math.round(rect.width*ratio)),height=Math.max(1,Math.round(rect.height*ratio));if(orbitCanvas.width!==width||orbitCanvas.height!==height){orbitCanvas.width=width;orbitCanvas.height=height}return{width,height,ratio}}
const fmt=value=>`${value.toFixed(3)} km/s`,altitude=radius=>radius-EARTH_RADIUS_KM;
const fmtSigned=value=>`${value>=0?'+':'−'}${Math.abs(value).toFixed(3)} km/s`;
const circlePoints=(radius,start=0,end=Math.PI*2,count=360)=>{const points=[];for(let i=0;i<=count;i++){const angle=start+(end-start)*i/count;points.push([radius*Math.cos(angle),radius*Math.sin(angle)])}return points};
const entryPoints=(count=360)=>{const points=[];for(let i=0;i<=count;i++)points.push(stateOnEllipse(EARTH_MU_KM3_S2,model.entryPerigee,model.entryApogee,-Math.PI+2*Math.PI*i/count).position);return points};
const transferPosition=anomaly=>stateOnConic(EARTH_MU_KM3_S2,model.transferConic.p,model.transferConic.e,anomaly,model.burnDirection).position;
const transferPoints=(count=240)=>{const points=[];for(let i=0;i<=count;i++)points.push(transferPosition(Math.PI*i/count));return points};

function phaseAt(value){
  if(value<boundaries.burn1Start){const f=value/boundaries.burn1Start,angle=model.burnAngle-2*Math.PI+2*Math.PI*f;return{stage:'entry',label:'Coast on entry orbit',position:stateOnEllipse(EARTH_MU_KM3_S2,model.entryPerigee,model.entryApogee,angle).position}}
  if(value<boundaries.burn1End)return{stage:'burn1',label:'Burn 1 · enter selected GTO',position:model.entryState.position,pulse:(value-boundaries.burn1Start)/(boundaries.burn1End-boundaries.burn1Start)};
  if(value<boundaries.burn2Start){const f=(value-boundaries.burn1End)/(boundaries.burn2Start-boundaries.burn1End);return{stage:'gto',label:'GTO coast to GEO apoapsis',position:transferPosition(Math.PI*f)}}
  const apogee=transferPosition(Math.PI);if(value<boundaries.burn2End)return{stage:'burn2',label:'Burn 2 · circularize at GEO',position:apogee,pulse:(value-boundaries.burn2Start)/(boundaries.burn2End-boundaries.burn2Start)};
  const f=(value-boundaries.burn2End)/(1-boundaries.burn2End),angle=model.burnDirection+Math.PI+2*Math.PI*f;return{stage:'geo',label:'Circular GEO',position:[GEO_RADIUS_KM*Math.cos(angle),GEO_RADIUS_KM*Math.sin(angle)]};
}

function drawVectorArrow(point,vector,label,color,project,ratio){const [x,y]=project(point),screen=[vector[0],-vector[1]],norm=Math.hypot(...screen)||1,length=44*ratio,tx=x+screen[0]/norm*length,ty=y+screen[1]/norm*length,angle=Math.atan2(ty-y,tx-x);ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=2*ratio;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(tx,ty);ctx.stroke();ctx.beginPath();ctx.moveTo(tx,ty);ctx.lineTo(tx-9*ratio*Math.cos(angle-.5),ty-9*ratio*Math.sin(angle-.5));ctx.lineTo(tx-9*ratio*Math.cos(angle+.5),ty-9*ratio*Math.sin(angle+.5));ctx.closePath();ctx.fill();ctx.font=`${10*ratio}px ui-monospace,monospace`;ctx.fillText(label,tx+7*ratio,ty)}
function drawOrbit(){
  const {width,height,ratio}=canvasSize(),cx=width/2,cy=height/2,padding=54*ratio,scale=Math.min(width-2*padding,height-2*padding)/(2*GEO_RADIUS_KM*1.06),project=point=>[cx+point[0]*scale,cy-point[1]*scale],phase=phaseAt(Number(progress.value)/1000);ctx.clearRect(0,0,width,height);
  const path=(points,color,widthPx=1,dash=[])=>{ctx.beginPath();points.forEach((point,index)=>{const [x,y]=project(point);index?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle=color;ctx.lineWidth=widthPx*ratio;ctx.setLineDash(dash.map(value=>value*ratio));ctx.stroke();ctx.setLineDash([])};
  path(entryPoints(),colors.entry,phase.stage==='entry'?3:1.4);path(transferPoints(),colors.gto,phase.stage==='gto'?3:1.5);path(circlePoints(GEO_RADIUS_KM),colors.geo,phase.stage==='geo'?3:1.4,[5,4]);
  ctx.fillStyle='#227eaf';ctx.shadowColor=colors.entry;ctx.shadowBlur=14*ratio;ctx.beginPath();ctx.arc(cx,cy,Math.max(7*ratio,EARTH_RADIUS_KM*scale),0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;
  const apogee=transferPosition(Math.PI),apogeeDirection=[-Math.sin(model.burnDirection+Math.PI),Math.cos(model.burnDirection+Math.PI)];drawVectorArrow(model.entryState.position,model.deltaVelocity,'① Δv₁',colors.gto,project,ratio);drawVectorArrow(apogee,apogeeDirection,'② Δv₂',colors.geo,project,ratio);
  const [sx,sy]=project(phase.position);if(phase.pulse!==undefined){const radius=(8+16*Math.sin(Math.PI*phase.pulse))*ratio;ctx.strokeStyle=phase.stage==='burn1'?colors.gto:colors.geo;ctx.lineWidth=2*ratio;ctx.globalAlpha=.85;ctx.beginPath();ctx.arc(sx,sy,radius,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}ctx.fillStyle='#fff';ctx.shadowColor='#fff';ctx.shadowBlur=12*ratio;ctx.beginPath();ctx.arc(sx,sy,5*ratio,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;
}

function updateStage(){const phase=phaseAt(Number(progress.value)/1000);$('#progressOutput').textContent=phase.label;$('#phaseNote').textContent=phase.stage==='entry'?`Coasting to ${burnAngle.value}° from entry-orbit perigee.`:phase.stage==='burn1'?`Keplerian vector burn: ΔvR = ${fmtSigned(model.deltaRadialSpeed)} cancels radial motion and ΔvT = ${fmtSigned(model.deltaTransverseSpeed)} sets the GTO periapsis speed.`:phase.stage==='gto'?`Coast ${Math.round(model.transferTimeSeconds/60)} minutes to the opposite side of Earth at GEO radius.`:phase.stage==='burn2'?`Add ${fmt(model.secondDeltaV)} prograde at apoapsis to raise periapsis and circularize.`:'The spacecraft now remains in circular geostationary orbit.';document.querySelectorAll('[data-stage]').forEach(item=>item.classList.toggle('active',item.dataset.stage===phase.stage));drawOrbit()}
function updateModel(){if(Number(apogeeAltitude.value)<Number(perigeeAltitude.value))apogeeAltitude.value=perigeeAltitude.value;model=gtoFromEntryScenario({perigeeAltitudeKm:Number(perigeeAltitude.value),apogeeAltitudeKm:Number(apogeeAltitude.value),burnAngleDeg:Number(burnAngle.value)});$('#perigeeAltitudeOutput').textContent=`${perigeeAltitude.value} km`;$('#apogeeAltitudeOutput').textContent=`${apogeeAltitude.value} km`;$('#burnAngleOutput').textContent=`${burnAngle.value}°`;$('#firstDv').textContent=fmt(model.firstDeltaV);$('#firstDvRadial').textContent=fmtSigned(model.deltaRadialSpeed);$('#firstDvTangential').textContent=fmtSigned(model.deltaTransverseSpeed);$('#secondDv').textContent=fmt(model.secondDeltaV);$('#totalDv').textContent=fmt(model.totalDeltaV);$('#transferTime').textContent=`${(model.transferTimeSeconds/3600).toFixed(2)} h`;$('#burnAltitude').textContent=`${Math.round(altitude(model.entryState.radius)).toLocaleString()} km`;$('#gtoApogee').textContent=`${Math.round(altitude(model.transferConic.apoapsis)).toLocaleString()} km`;document.querySelectorAll('[data-angle]').forEach(button=>button.classList.toggle('accent',Number(button.dataset.angle)===Number(burnAngle.value)));updateStage()}

[perigeeAltitude,apogeeAltitude,burnAngle].forEach(input=>input.addEventListener('input',()=>{playing=false;$('#play').textContent='Play';progress.value='0';updateModel()}));document.querySelectorAll('[data-angle]').forEach(button=>button.addEventListener('click',()=>{burnAngle.value=button.dataset.angle;progress.value='0';playing=false;$('#play').textContent='Play';updateModel()}));progress.addEventListener('input',()=>{playing=false;$('#play').textContent='Play';updateStage()});$('#play').addEventListener('click',()=>{if(Number(progress.value)>=1000)progress.value='0';playing=!playing;$('#play').textContent=playing?'Pause':'Play';lastFrame=performance.now()});$('#reset').addEventListener('click',()=>{playing=false;$('#play').textContent='Play';progress.value='0';updateStage()});new ResizeObserver(drawOrbit).observe($('#viewport'));
function animate(time){if(playing){const elapsed=Math.min(50,time-lastFrame);lastFrame=time;let value=Number(progress.value)+elapsed*.075;if(value>=1000){value=1000;playing=false;$('#play').textContent='Replay'}progress.value=String(value);updateStage()}requestAnimationFrame(animate)}
updateModel();requestAnimationFrame(animate);
