import {EARTH_MU_KM3_S2,EARTH_RADIUS_KM,GEO_RADIUS_KM,gtoInjectionScenario,sampleConic,stateOnEllipse} from '../js/oberth.js?v=20260902-1';

const $=selector=>document.querySelector(selector);
const perigeeAltitude=$('#perigeeAltitude'),apogeeAltitude=$('#apogeeAltitude'),burnAngle=$('#burnAngle');
const orbitCanvas=$('#orbitCanvas'),orbitContext=orbitCanvas.getContext('2d'),chartCanvas=$('#chartCanvas'),chartContext=chartCanvas.getContext('2d');
const colors={cyan:'#54d6dd',orange:'#ffb14e',muted:'#90a1a8',green:'#8bd99d'};let model;
function canvasSize(canvas){const rect=canvas.getBoundingClientRect(),ratio=Math.min(2,devicePixelRatio||1),width=Math.max(1,Math.round(rect.width*ratio)),height=Math.max(1,Math.round(rect.height*ratio));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height}return{width,height,ratio}}
const altitude=radius=>radius-EARTH_RADIUS_KM,fmt=value=>`${value.toFixed(3)} km/s`;
function ellipsePoints(rp,ra,count=360){const points=[];for(let index=0;index<=count;index++)points.push(stateOnEllipse(EARTH_MU_KM3_S2,rp,ra,-Math.PI+2*Math.PI*index/count).position);return points}

function drawOrbit(){
  const {width,height,ratio}=canvasSize(orbitCanvas),ctx=orbitContext,cx=width/2,cy=height/2,padding=42*ratio,scale=Math.min(width-2*padding,height-2*padding)/(2*GEO_RADIUS_KM*1.08),project=point=>[cx+point[0]*scale,cy-point[1]*scale];ctx.clearRect(0,0,width,height);
  const path=(points,color,widthPx=1,dash=[])=>{ctx.beginPath();points.forEach((point,index)=>{const [x,y]=project(point);index?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle=color;ctx.lineWidth=widthPx*ratio;ctx.setLineDash(dash.map(value=>value*ratio));ctx.stroke();ctx.setLineDash([])};
  const circle=(radius,color,dash=[])=>{ctx.beginPath();ctx.arc(cx,cy,radius*scale,0,2*Math.PI);ctx.strokeStyle=color;ctx.lineWidth=ratio;ctx.setLineDash(dash.map(value=>value*ratio));ctx.stroke();ctx.setLineDash([])};
  circle(GEO_RADIUS_KM,colors.green,[5,5]);path(ellipsePoints(model.periapsis,GEO_RADIUS_KM),colors.green,1,[3,5]);path(ellipsePoints(model.periapsis,model.apoapsis),colors.cyan,1.8);path(sampleConic(model.burn.conic,360),colors.orange,2.5);
  ctx.fillStyle='#227eaf';ctx.shadowColor='#54d6dd';ctx.shadowBlur=14*ratio;ctx.beginPath();ctx.arc(cx,cy,EARTH_RADIUS_KM*scale,0,2*Math.PI);ctx.fill();ctx.shadowBlur=0;
  const [bx,by]=project(model.state.position);ctx.fillStyle=colors.orange;ctx.shadowColor=colors.orange;ctx.shadowBlur=10*ratio;ctx.beginPath();ctx.arc(bx,by,5*ratio,0,2*Math.PI);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle=colors.orange;ctx.font=`${10*ratio}px ui-monospace,monospace`;ctx.fillText('burn',bx+9*ratio,by-8*ratio);
}

function drawChart(){
  const {width,height,ratio}=canvasSize(chartCanvas),ctx=chartContext,left=58*ratio,right=22*ratio,top=18*ratio,bottom=32*ratio,pw=width-left-right,ph=height-top-bottom,args={perigeeAltitudeKm:Number(perigeeAltitude.value),apogeeAltitudeKm:Number(apogeeAltitude.value)},samples=[];for(let angle=0;angle<=180;angle+=2)samples.push([angle,gtoInjectionScenario({...args,burnAngleDeg:angle}).burn.deltaV]);
  const minimum=Math.min(...samples.map(point=>point[1]))*.96,maximum=Math.max(...samples.map(point=>point[1]))*1.04||1,x=angle=>left+pw*angle/180,y=value=>top+ph*(maximum-value)/(maximum-minimum||1);ctx.clearRect(0,0,width,height);ctx.font=`${9*ratio}px ui-monospace,monospace`;ctx.fillStyle=colors.muted;ctx.strokeStyle='rgba(180,218,225,.16)';ctx.lineWidth=ratio;
  for(let index=0;index<=4;index++){const value=minimum+(maximum-minimum)*index/4,py=y(value);ctx.beginPath();ctx.moveTo(left,py);ctx.lineTo(left+pw,py);ctx.stroke();ctx.textAlign='right';ctx.fillText(value.toFixed(2),left-7*ratio,py+3*ratio)}for(const angle of [0,45,90,135,180]){ctx.textAlign='center';ctx.fillText(`${angle}°`,x(angle),height-10*ratio)}
  ctx.strokeStyle=colors.orange;ctx.lineWidth=2.2*ratio;ctx.beginPath();samples.forEach(([angle,value],index)=>index?ctx.lineTo(x(angle),y(value)):ctx.moveTo(x(angle),y(value)));ctx.stroke();ctx.fillStyle='#fff';ctx.strokeStyle='#071014';ctx.lineWidth=2*ratio;ctx.beginPath();ctx.arc(x(Number(burnAngle.value)),y(model.burn.deltaV),5*ratio,0,2*Math.PI);ctx.fill();ctx.stroke();ctx.save();ctx.translate(13*ratio,top+ph/2);ctx.rotate(-Math.PI/2);ctx.fillStyle=colors.muted;ctx.textAlign='center';ctx.fillText('injection Δv (km/s)',0,0);ctx.restore();
}

function update(){
  apogeeAltitude.min=perigeeAltitude.value;if(Number(apogeeAltitude.value)<Number(perigeeAltitude.value))apogeeAltitude.value=perigeeAltitude.value;model=gtoInjectionScenario({perigeeAltitudeKm:Number(perigeeAltitude.value),apogeeAltitudeKm:Number(apogeeAltitude.value),burnAngleDeg:Number(burnAngle.value)});
  $('#perigeeAltitudeOutput').textContent=`${perigeeAltitude.value} km`;$('#apogeeAltitudeOutput').textContent=`${apogeeAltitude.value} km`;$('#burnAngleOutput').textContent=`${burnAngle.value}°`;$('#selectedDv').textContent=fmt(model.burn.deltaV);$('#perigeeDv').textContent=fmt(model.optimum.deltaV);$('#penalty').textContent=`+${model.penalty.toFixed(3)} km/s`;$('#circularizationDv').textContent=fmt(model.circularizationDeltaV);$('#resultPerigee').textContent=`${Math.round(altitude(model.burn.conic.periapsis)).toLocaleString()} km`;$('#resultApogee').textContent=`${Math.round(altitude(model.burn.conic.apoapsis)).toLocaleString()} km`;
  const angle=Number(burnAngle.value),circular=Number(perigeeAltitude.value)===Number(apogeeAltitude.value),error=Math.round(model.apogeeError);$('#burnNote').textContent=circular?'A circular orbit has no unique perigee: every burn point is dynamically equivalent and produces the same rotated GTO.':angle===0?`Perigee is the optimum. This burn produces the intended ${Math.round(altitude(GEO_RADIUS_KM)).toLocaleString()} km apogee.`:angle===180?`Apogee is the slowest point and needs ${model.penalty.toFixed(3)} km/s more. Its resulting apogee misses GEO by ${Math.abs(error).toLocaleString()} km.`:`This burn matches GTO energy but not its apsides; resulting apogee error is ${error.toLocaleString()} km.`;document.querySelectorAll('[data-angle]').forEach(button=>button.classList.toggle('accent',Number(button.dataset.angle)===angle));drawOrbit();drawChart();
}

[perigeeAltitude,apogeeAltitude,burnAngle].forEach(input=>input.addEventListener('input',update));document.querySelectorAll('[data-angle]').forEach(button=>button.addEventListener('click',()=>{burnAngle.value=button.dataset.angle;update()}));$('#circularPreset').addEventListener('click',()=>{perigeeAltitude.value='300';apogeeAltitude.value='300';burnAngle.value='0';update()});$('#eccentricPreset').addEventListener('click',()=>{perigeeAltitude.value='300';apogeeAltitude.value='2000';burnAngle.value='0';update()});new ResizeObserver(()=>{drawOrbit();drawChart()}).observe($('#viewport'));new ResizeObserver(drawChart).observe($('#chartPanel'));update();
