import {AU_KM,EARTH_YEAR_DAYS,MOON_DISTANCE_KM,effectivePotential,hillRadius,lagrangePoints,sphereOfInfluence} from '../js/three-body.js?v=20260827-1';

const $=selector=>document.querySelector(selector),canvas=$('#canvas'),ctx=canvas.getContext('2d'),points=lagrangePoints(),soi=sphereOfInfluence(),hill=hillRadius();
let elapsedDays=0,playing=false,lastTime=performance.now();
const colors={earth:'#54d6dd',sun:'#ffe09a',lagrange:'#ffb14e',soi:'#8bd99d',hill:'#ff766d',muted:'#90a1a8'};
const rotate=(point,angle)=>[point[0]*Math.cos(angle)-point[1]*Math.sin(angle),point[0]*Math.sin(angle)+point[1]*Math.cos(angle)];
function sizeCanvas(){const rect=canvas.getBoundingClientRect(),ratio=Math.min(2,devicePixelRatio||1),width=Math.round(rect.width*ratio),height=Math.round(rect.height*ratio);if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height}return{width,height,ratio}}
function draw(){
  const {width,height,ratio}=sizeCanvas(),earthView=$('#viewScale').value==='earth',inertial=$('#referenceFrame').value==='inertial',angle=inertial?Math.PI*2*elapsedDays/EARTH_YEAR_DAYS:0,extent=earthView?2.15e6:1.18*AU_KM,center=earthView?points.earth:[0,0],scale=Math.min(width,height)/(2*extent),project=raw=>{const relative=[raw[0]*AU_KM-center[0]*AU_KM,raw[1]*AU_KM-center[1]*AU_KM],rotated=rotate(relative,angle);return[width/2+rotated[0]*scale,height/2-rotated[1]*scale]};
  ctx.clearRect(0,0,width,height);
  if($('#showPotential').checked&&!earthView&&!inertial){for(let iy=0;iy<24;iy++)for(let ix=0;ix<36;ix++){const x=-1.2+2.4*(ix+.5)/36,y=-1.1+2.2*(iy+.5)/24,potential=effectivePotential(x,y,points.mu),intensity=Math.max(0,Math.min(.15,(potential-1.45)*.18));ctx.fillStyle=`rgba(84,214,221,${intensity})`;ctx.fillRect(ix*width/36,iy*height/24,width/36+1,height/24+1)}}
  if(!earthView){const [sx,sy]=project(points.sun);ctx.strokeStyle='rgba(84,214,221,.28)';ctx.lineWidth=ratio;ctx.beginPath();ctx.arc(sx,sy,AU_KM*scale,0,Math.PI*2);ctx.stroke()}
  const earthPoint=project(points.earth),sunPoint=project(points.sun);
  const circle=(radius,color,dashed=false)=>{ctx.beginPath();ctx.arc(earthPoint[0],earthPoint[1],radius*scale,0,Math.PI*2);ctx.strokeStyle=color;ctx.lineWidth=1.6*ratio;ctx.setLineDash(dashed?[5*ratio,4*ratio]:[]);ctx.stroke();ctx.setLineDash([])};
  if($('#showSoi').checked)circle(soi,colors.soi,true);if($('#showHill').checked)circle(hill,colors.hill);
  if(earthView){circle(MOON_DISTANCE_KM,'rgba(180,218,225,.35)',true);const direction=rotate([-1,0],angle),labelX=width/2+direction[0]*width*.29,labelY=height/2-direction[1]*height*.29;ctx.strokeStyle=colors.sun;ctx.lineWidth=2*ratio;ctx.beginPath();ctx.moveTo(width/2,height/2);ctx.lineTo(width/2+direction[0]*width*.42,height/2-direction[1]*height*.42);ctx.stroke();ctx.fillStyle=colors.sun;ctx.font=`${11*ratio}px ui-monospace,monospace`;ctx.fillText('toward Sun',labelX+7*ratio,labelY-7*ratio)}
  const marker=(point,color,radius,label,offset=[8,-8])=>{const [x,y]=project(point);ctx.fillStyle=color;ctx.shadowColor=color;ctx.shadowBlur=10*ratio;ctx.beginPath();ctx.arc(x,y,radius*ratio,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle=colors.muted;ctx.font=`${10*ratio}px ui-monospace,monospace`;ctx.fillText(label,x+offset[0]*ratio,y+offset[1]*ratio)};
  if(!earthView)marker(points.sun,colors.sun,7,'Sun',[10,-9]);marker(points.earth,colors.earth,earthView?7:4,earthView?'Earth':'Earth · switch scale for L1/L2',[9,-8]);
  const visible=earthView?['L1','L2']:['L3','L4','L5'];for(const name of visible)marker(points[name],colors.lagrange,3,name,name==='L5'?[8,15]:[8,-8]);
  if(earthView){ctx.fillStyle=colors.muted;ctx.font=`${10*ratio}px ui-monospace,monospace`;ctx.fillText('Moon orbit',earthPoint[0]+MOON_DISTANCE_KM*scale+5*ratio,earthPoint[1]);ctx.fillStyle=colors.soi;ctx.fillText('SOI',earthPoint[0]+soi*scale+5*ratio,earthPoint[1]-14*ratio);ctx.fillStyle=colors.hill;ctx.fillText('Hill',earthPoint[0]+hill*scale+5*ratio,earthPoint[1]+16*ratio)}
}
function readouts(){const km=value=>`${Math.round(value).toLocaleString()} km`;$('#soiRadius').textContent=km(soi);$('#hillRadius').textContent=km(hill);$('#soiMoon').textContent=`${(soi/MOON_DISTANCE_KM).toFixed(2)} ×`;$('#hillMoon').textContent=`${(hill/MOON_DISTANCE_KM).toFixed(2)} ×`;$('#l1Distance').textContent=km((points.earth[0]-points.L1[0])*AU_KM);$('#l2Distance').textContent=km((points.L2[0]-points.earth[0])*AU_KM);$('#timeScaleOutput').textContent=`${$('#timeScale').value} days/s`}
document.querySelectorAll('select,input').forEach(control=>control.addEventListener('input',()=>{readouts();draw()}));$('#play').addEventListener('click',()=>{playing=!playing;$('#play').textContent=playing?'Pause':'Play';lastTime=performance.now()});$('#reset').addEventListener('click',()=>{elapsedDays=0;playing=false;$('#play').textContent='Play';draw()});new ResizeObserver(draw).observe($('#viewport'));
function animate(time){if(playing){elapsedDays+=(time-lastTime)/1000*Number($('#timeScale').value);draw()}lastTime=time;requestAnimationFrame(animate)}readouts();draw();requestAnimationFrame(animate);
